name-template: 'v$RESOLVED_VERSION ✨'
tag-template: 'v$RESOLVED_VERSION'

categories:

  - title: 🔴 BREAKING CHANGES
    labels:
      - BREAKING CHANGE

  - title: 🧩 Atoms
    labels:
      - '@atoms'

  - title: 🧩 Molecules
    labels:
      - '@molecules'

  - title: 🧩 Organisms
    labels:
      - '@organisms'

  - title: 🐞 Bug Fixes
    labels:
      - fix
      - bug

  - title: 🪐 Internal
    labels:
      - lib
      - configuration
      - packages
      - build
      - dependencies

change-template: '- $TITLE #$NUMBER (@$AUTHOR)'
template: |
  $CHANGES

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
