categories:
  - title: 🧩 Atoms
    labels:
      - '@atoms'

  - title: 🧩 Molecules
    labels:
      - '@molecules'

  - title: 🧩 Organisms
    labels:
      - '@organisms'
  
  - title: 🧩 Templates
    labels:
      - '@templates'

  - title: 🪐 Internal
    labels:
      - lib
      - configuration
      - packages
      - build
      - dependencies

  - title: '⚠️ Breaking changes'
    label: 'BREAKING CHANGES'

  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'

  - title: '📚 Documentation'
    label: 'documentation'

  - title: '🧪 Tests'
    label: 'tests'

  - title: '🏎 Optimizations'
    label: 'optimizations'

version-resolver:
  major:
    labels:
      - 'BREAKING CHANGES'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
      - 'dependencies'
  patch:
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'optimizations'
  default: patch

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

change-template: '- $TITLE #$NUMBER (@$AUTHOR)'
template: |
  $CHANGES
