name: Publish Package CI

on:
  workflow_dispatch:
    inputs:
      woly:
        description: 'Set "yes" to run publish'
        required: true
        default: 'no'
      calendar:
        description: 'Set "yes" to run publish'
        required: true
        default: 'no'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Create NPM config
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Publish woly to NPM
        if: github.events.inputs.woly == 'yes'
        working-directory: 'dist/woly'
        run: npm publish

      - name: Publish calendar to NPM
        if: github.events.inputs.calendar == 'yes'
        working-directory: 'dist/calendar'
        run: npm publish
