name: NPM Package CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['13', '12', '10', '8']

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Publish to NPM
        uses: pascalgn/npm-publish-action@1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
